"""
Prompts module initialization
"""
from packages.prompts.templates import (
    QA_SYSTEM_PROMPT,
    QA_USER_PROMPT_TEMPLATE,
    SOP_GENERATION_PROMPT,
    MEETING_INTELLIGENCE_PROMPT,
    CONFLICT_DETECTION_PROMPT,
    ONBOARDING_PROMPT,
)

__all__ = [
    "QA_SYSTEM_PROMPT",
    "QA_USER_PROMPT_TEMPLATE",
    "SOP_GENERATION_PROMPT",
    "MEETING_INTELLIGENCE_PROMPT",
    "CONFLICT_DETECTION_PROMPT",
    "ONBOARDING_PROMPT",
]
